version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
        #networks:
        #- main
  web:
    build: .
    image: app
    command: bash entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: $SECRET_KEY
        #networks:
        #- main
  ui:
    container_name: kanban_ui
    restart: always
    command: npm start
    depends_on:
      - web
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
       - "3000:3000"
      #networks:
      #- main

volumes:
  db:

    #networks:
    #main:
    #driver: bridge
