version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
        #networks:
        #- main
  web:
    build: .
    image: app
    command: bash /src/backend/entrypoint.sh
    volumes:
      - .:/src
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      SECRET_KEY: $SECRET_KEY
        #networks:
        #- main
  ui:
    container_name: kanban_ui
    restart: always
    depends_on:
      - web
    build:
      context: .
      dockerfile: Dockerfile.ui
    volumes:
      - ./kanban-ui:/kanban-ui
      #networks:
      #- main
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/logs/nginx
      - ./kanban-ui/build:/var/www/kanban-ui
    depends_on:
      - web
volumes:
  db:

    #networks:
    #main:
    #driver: bridge
