# syntax=docker/dockerfile:1
FROM node:lts-slim as build

WORKDIR /src/kanban-ui

COPY kanban-ui/package.json kanban-ui/package-lock.json ./
RUN npm install

COPY kanban-ui .

RUN npm run build

FROM nginx:latest
COPY ./nginx/conf.d/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/kanban-ui/build /var/www/kanban-ui

CMD ["nginx", "-g", "daemon off;"]
