# Generated by Django 3.2.12 on 2022-10-29 20:52

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20221029_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbancard',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='kanbancard',
            name='position',
            field=models.PositiveIntegerField(default=kanban.models.KanbanCard.get_default_position),
        ),
        migrations.AlterField(
            model_name='kanbancolumn',
            name='position',
            field=models.PositiveIntegerField(default=kanban.models.KanbanColumn.get_default_position),
        ),
    ]
