name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  backend_unit_tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: Set up DB
        run: |
          python3 backend/manage.py makemigrations
          python3 backend/manage.py migrate
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
      - name: Run kanban tests
        run: python3 backend/manage.py test kanban
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
  
  graph-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Django Action
        uses: noah-software/django_action@c045cd21a1d58a0d39b441f729ad12c8062da155
        with:
          project_path: backend
          output_path: ../docs/db_schema.png
          pip_path: backend/requirements.txt
        env:
          SECRET_KEY: TESTING_KEY
